# Generated by Django 5.0.6 on 2024-06-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.genre')),
            ],
        ),
    ]
