# Generated by Django 5.0.6 on 2024-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('title', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField()),
                ('add_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
